# Generated by Django 5.1.2 on 2024-10-20 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horta', '0004_rename_descricao_cultura_desc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horta',
            name='comunitaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horta',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='hortas_comunitarias', to=settings.AUTH_USER_MODEL),
        ),
    ]
